---
title: "Data Visualization for Paper"
author: "Alice Mee Seon Chung and Ningyin Xu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE,
                      fig.width=7, fig.height=5)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(plm)
library(coefplot)
library(corrplot)
library(SparseM)
library(sp)
set.seed(1234)
theme_set(theme_minimal())
options(digits = 3)
options(scipen=999)
options(warn=-1)
setwd("~/Desktop/2018SPRING/DV/fp-nxu-achung")
# Load all the dataframes and other pre-defined variables to use later
load("data.RData")
```

# Graphs

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Scatter plot of personal income and gdp in both 2010 and 2014 
ggplot(data =joined_14_prov3,
             aes(x =GDP, y = mean_income))+ 
  geom_point(alpha = 0.7, aes(col = 'red'))+
  geom_point(data = joined_10_prov3, alpha = 0.7, aes(col = 'blue'))+
  labs(title = "Personal Income vs. GDP",
       x = "GDP",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")+
  scale_color_manual(labels = c(2010, 2014), values = c('#F8766D','#00BFC4')) +
  guides(col=guide_legend(title='Year'))+
  theme(legend.position = "right")
```

## China Map

```{r, echo=FALSE }
# Whole China Map
# ch contains longitude and latitude data of whole china
ggplot(ch, aes(x=long, y=lat, map_id = provcd))+
        geom_polygon(data= ch,  aes(x=long, y=lat, fill=diffincome ))+
        scale_fill_gradient(low="white", high="#00BFC4", 
                            name="Difference of Personal Income",
                            limits=c(-2000,13000))+
        geom_path(color="black", size=0.3) +
        coord_fixed()+
        expand_limits(x = 100, y = ch_midwest$lat) +
        labs(title = 'Difference of Personal Income between 2014 and 2010 in China',
          caption ='Source: China Family Panel Studies\nNote: The region colored in grey is the area that does not have record in data.')+
        theme(axis.line=element_blank(),
              axis.text.x=element_blank(),
              axis.text.y=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.background=element_blank(),
              panel.border=element_blank(),
              panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              plot.background=element_blank())
```

```{r, echo=FALSE}
# East China
# ch_east contains longitude and latitude data of east China
ggplot(ch_east, aes(x=long, y=lat, map_id = provcd))+
        geom_polygon(data= ch_east,  aes(x=long, y=lat, fill=diffincome ))+
        scale_fill_gradient(low="white", high="#00BFC4", 
                            name="Difference of Personal Income",
                            limits=c(-2000,13000))+
        geom_path(color="black", size=0.3) +
        coord_fixed()+
        expand_limits(x = 140, y = ch_east$lat) +
        labs(title = 'Difference of Personal Income between 2014 and 2010 in East China',
          caption ='Source: China Family Panel Studies\nNote: The region colored in grey is the area that does not have record in data.')+
        theme(axis.line=element_blank(),
              axis.text.x=element_blank(),
              axis.text.y=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.background=element_blank(),  
              panel.border=element_blank(),
              panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              plot.background=element_blank())
```

```{r, echo=FALSE}
# Midwest China
# ch_midwest contains longitude and latitude data of midwest China
ggplot(ch_midwest, aes(x=long, y=lat, map_id = provcd))+
        geom_polygon(data= ch_midwest,  aes(x=long, y=lat, fill=diffincome ))+
        scale_fill_gradient(low="white", high="#00BFC4", 
                            name="Difference of Personal Income",
                            limits=c(-2000,13000))+
        geom_path(color="black", size=0.3) +
        coord_fixed()+
        expand_limits(x = ch_midwest$long, y = ch_midwest$lat) +
        labs(title = 'Difference of Personal Income between 2014 and 2010 in Midwest China',
          caption ='Source: China Family Panel Studies\nNote: The region colored in grey is the area that does not have record in data.')+
        theme(axis.line=element_blank(),
              axis.text.x=element_blank(),
              axis.text.y=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.background=element_blank(),
              panel.border=element_blank(),
              panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              plot.background=element_blank())
```

## Distribution of each variable and Relationship with Personal Income in China

### Individual Level

```{r, echo=FALSE}
# Age
# Generate temporal dataframe only for age variable
temp <- joined_n %>%
  select(community_2010, community_2014,
         age_2010, age_2014) %>%
  filter(!is.na(age_2010) & !is.na(age_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "age_2010", "age_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time))

# Distribution
ggplot(data = temp, aes(x = age)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Age",
       x = "Age",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(income_2010, income_2014,
         age_2010, age_2014) %>%
  filter(!is.na(age_2010) & !is.na(age_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("income_2010", "income_2014",
                      "age_2010", "age_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  group_by(age, time) %>%
  summarise(mean_inc = mean(income, na.rm = T)) %>%
  ggplot(aes(x = age, y=mean_inc, color = time)) +
  geom_point(alpha = 0.2) +
  geom_smooth(alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Age",
       x = "Age",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Age-Square
# Distribution
joined_n %>%
  select(community_2010, community_2014,
         age_2010, age_2014) %>%
  filter(!is.na(age_2010) & !is.na(age_2014)) %>%
  mutate(agesquare_2010 = age_2010 ^ 2,
         agesquare_2014 = age_2014^2) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "agesquare_2010", "agesquare_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = agesquare)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Age-Square",
       x = "Age^2",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
  joined_n %>%
  select(income_2010, income_2014,
         age_2010, age_2014) %>%
  filter(!is.na(age_2010) & !is.na(age_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  mutate(agesquare_2010 = age_2010 ^ 2,
         agesquare_2014 = age_2014^2) %>%
  reshape(direction = "long",
          varying = c("income_2010", "income_2014",
                      "age_2010", "age_2014",
                      "agesquare_2010", "agesquare_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  group_by(agesquare, time) %>%
  summarise(mean_inc = mean(income, na.rm = T)) %>%
  ggplot(aes(x = agesquare, y=mean_inc, color = time)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Age^2",
       x = "Age^2",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Gender
# Distribtuion
joined_n %>%
  select(community_2010, community_2014,
         gender_2010, gender_2014) %>%
  filter(!is.na(gender_2010) & !is.na(gender_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "gender_2010", "gender_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         gender = as.factor(gender)) %>%
  ggplot(aes(x = gender)) +
  geom_bar(position = "dodge", aes(fill = time),
           width = 0.5) +
  labs(title = "Distribution of Gender",
       x = "Gender",
       y = "Count",
       color = "Year",
       caption = "Source: China Family Panel Studies")
  
# Relationship
joined_n %>%
  select(income_2010, income_2014,
         gender_2010, gender_2014) %>%
  filter(!is.na(gender_2010) & !is.na(gender_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("income_2010", "income_2014",
                      "gender_2010", "gender_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         gender = as.factor(gender)) %>%
  ggplot(aes(x = gender, y=income, color = time)) +
  geom_boxplot(position="dodge",
               alpha = 0.7) +
  scale_y_continuous(limits = c(0, income_q99)) +
  labs(title = "Personal Income vs. Gender",
       subtitle = "excluding top 1% income",
       x = "Gender",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Education Years
# Distribtuion
joined_n %>%
  select(community_2010, community_2014,
         educ_2010, educ_2014) %>%
  filter(!is.na(educ_2010) & !is.na(educ_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "educ_2010", "educ_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = educ)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Education Years",
       x = "Education Years",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

#Relationship
joined_n %>%
  select(income_2010, income_2014,
         educ_2010, educ_2014) %>%
  filter(!is.na(educ_2010) & !is.na(educ_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("income_2010", "income_2014",
                      "educ_2010", "educ_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  group_by(educ, time) %>%
  summarise(mean_inc = mean(income, na.rm = T)) %>%
  ggplot(aes(x = educ, y=mean_inc, color = time)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm",alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Education Years",
       x = "Education Years",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

### Residential Community Level

```{r, echo=FALSE}
# The number of convenience stores
# Distribtuion
joined_n %>%
  select(community_2010, community_2014, 
         numconvenience_2010, numconvenience_2014) %>%
  filter(!is.na(numconvenience_2010) & !is.na(numconvenience_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "numconvenience_2010", "numconvenience_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = numconvenience)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Number of Convenience Stores in Communities",
       x = "Number of Convenience Stores",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         numconvenience_2010, numconvenience_2014) %>%
  filter(!is.na(numconvenience_2010) & !is.na(numconvenience_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "numconvenience_2010", "numconvenience_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = numconvenience, y=income, color = time)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", alpha=0.3, span=0.3) +
  ylim(0, 60000)+
  labs(title = "Personal Income vs. Number of Convenience Stores in Communities",
       x = "Number of Convenience Stores",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# The number of primary schools
# Distribtuion
joined_n  %>%
  select(community_2010, community_2014, 
         numprimarysch_2010, numprimarysch_2014) %>%
  filter(!is.na(numprimarysch_2010) & !is.na(numprimarysch_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "numprimarysch_2010", "numprimarysch_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = numprimarysch)) +
  geom_bar(position="dodge",aes(fill = time)) +
  labs(title = "Distribution of Number of Primary Schools in Communities",
       x = "Number of Primary Schools",
       y = "Count",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         numprimarysch_2010, numprimarysch_2014) %>%
  filter(!is.na(numprimarysch_2010) & !is.na(numprimarysch_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "numprimarysch_2010", "numprimarysch_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         numprimarysch = as.factor(numprimarysch)) %>%
  ggplot(aes(x = numprimarysch, y=income, color = time)) +
  geom_boxplot(position="dodge",
               varwidth = T,
               alpha = 0.5) +
  scale_y_continuous(limits = c(0, income_q99)) +
  labs(title = "Personal Income vs. Number of Primary Schools in Communities",
       subtitle = "excluding top 1% income, box width representing group size",
       x = "Number of Primary Schools",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# The number of hospitals 
# Distribution
joined_n %>%
  select(community_2010, community_2014,
         numhospital_2010, numhospital_2014) %>%
  filter(!is.na(numhospital_2010) & !is.na(numhospital_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "numhospital_2010", "numhospital_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = numhospital)) +
  geom_line(stat = "density", aes(color = time), alpha = 0.7) +
  labs(title = "Distribution of Number of Hospitals in Communities",
       x = "Number of Hospitals",
       y = "Count",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         numhospital_2010, numhospital_2014) %>%
  filter(!is.na(numhospital_2010) & !is.na(numhospital_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "numhospital_2010", "numhospital_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         numhospital = as.factor(numhospital)) %>%
  ggplot(aes(x = numhospital, y=income, color = time)) +
  geom_boxplot(position="dodge", 
               alpha = 0.7) +
  scale_y_continuous(limits = c(0, income_q99)) +
  labs(title = "Personal Income vs. Number of Hospitals in Communities",
       subtitle = "excluding top 1% income",
       x = "Number of Hospitals",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# The type of water source
# Distribtuion
joined_n  %>%
  select(community_2010, community_2014, 
         watersource_2010, watersource_2014) %>%
  filter(!is.na(watersource_2010) & !is.na(watersource_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "watersource_2010", "watersource_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = watersource)) +
  geom_bar(position="dodge", aes(fill = time)) +
  labs(title = "Types of Water Sources in Communities",
       x = "Type of Water Sources",
       y = "Count",
       color = "Year",
       caption = "Source: China Family Panel Studies")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         watersource_2010, watersource_2014) %>%
  filter(!is.na(watersource_2010) & !is.na(watersource_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "watersource_2010", "watersource_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = watersource, y=income, color = time)) +
  geom_boxplot(position="dodge",
               varwidth = T,
               alpha = 0.3) +
  scale_y_continuous(limits = c(0, income_q99)) +
  labs(title = "Personal Income vs. Types of Water Sources in Communities",
       subtitle = "excluding top 1% income, box width representing group size",
       x = "Type of Water Sources",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r, echo=FALSE}
# Pupulation
# Distribution
joined_n %>%
  select(community_2010, community_2014,
         pop_2010, pop_2014) %>%
  filter(!is.na(pop_2010) & !is.na(pop_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "pop_2010", "pop_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = pop)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Population in Communities",
       x = "Population",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         pop_2010, pop_2014) %>%
  filter(!is.na(pop_2010) & !is.na(pop_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "pop_2010", "pop_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  group_by(community, time) %>%
  summarise(mean_inc = mean(income, na.rm = T),
            mean_pop = mean(pop, na.rm=T)) %>%
  ggplot(aes(x = mean_pop, y=mean_inc, color = time)) +
  geom_smooth(method = "lm")+
  geom_point(alpha = 0.1) +
  labs(title = "Personal Income vs. Population in Communities",
       x = "Population",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Travel Time from County Committe to Nearest Town
# Distribtion
joined_n %>%
  select(community_2010, community_2014,
         timecommittenearesttown_2010, timecommittenearesttown_2014) %>%
  filter(!is.na(timecommittenearesttown_2010) & !is.na(timecommittenearesttown_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "timecommittenearesttown_2010", "timecommittenearesttown_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = timecommittenearesttown)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Travel Time to Nearest Town in Communities",
       x = "Travel Time (hours)",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         timecommittenearesttown_2010, timecommittenearesttown_2014) %>%
  filter(!is.na(timecommittenearesttown_2010) & !is.na(timecommittenearesttown_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "timecommittenearesttown_2010", "timecommittenearesttown_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  group_by(community, time) %>%
  summarise(mean_inc = mean(income, na.rm = T),
            mean_time = mean(timecommittenearesttown, na.rm=T)) %>%
  ggplot(aes(x = mean_time, y=mean_inc, color = time)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Travel Time to Nearest Town in Communities",
       x = "Travel Time from County Committe to Nearest Town",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Travel Time to County Seat to Nearest Town
# Distribtion
joined_n %>%
  select(community_2010, community_2014,
         timecommittecountycap_2010, timecommittecountycap_2014) %>%
  filter(!is.na(timecommittecountycap_2010) & !is.na(timecommittecountycap_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "timecommittecountycap_2010", "timecommittecountycap_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = timecommittecountycap)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Travel Time to County Seat in Communities",
       x = "Travel Time (hours)",
       y = "Density",
       color = "Year",
       caption = "Source: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         timecommittecountycap_2010, timecommittecountycap_2014) %>%
  filter(!is.na(timecommittecountycap_2010) & !is.na(timecommittecountycap_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "timecommittecountycap_2010", "timecommittecountycap_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         timecommittecountycap = as.numeric(timecommittecountycap)) %>%
  group_by(community, time) %>%
  summarise(mean_inc = mean(income, na.rm = T),
            mean_time = mean(timecommittecountycap, na.rm=T)) %>%
  ggplot(aes(x = mean_time, y=mean_inc, color = time)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Travel Time to County Seat in Communities",
       x = "Travel Time to County Seat",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Agricultural GDP
# Distribtion
joined_n %>%
  select(community_2010, community_2014,
         agrigdp_2010, agrigdp_2014) %>%
  filter(!is.na(agrigdp_2010) & !is.na(agrigdp_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "agrigdp_2010", "agrigdp_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = agrigdp)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Agricultural GDP in Communities",
       x = "Agricultural GDP",
       y = "Density",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         agrigdp_2010, agrigdp_2014) %>%
  filter(!is.na(agrigdp_2010) & !is.na(agrigdp_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "agrigdp_2010", "agrigdp_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         agrigdp = as.numeric(agrigdp)) %>%
  group_by(community, time) %>%
  summarise(mean_inc = mean(income, na.rm = T),
            mean_agrgdp = mean(agrigdp, na.rm=T)) %>%
  ggplot(aes(x = mean_agrgdp, y=mean_inc, color = time)) +
  geom_point(alpha = 0.1) +
  geom_smooth(alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Agricultural GDP in Communities",
       x = "Agricultural GDP",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Nonagricultural GDP
# Distribtion
joined_n %>%
  select(community_2010, community_2014,
         nonagrigdp_2010, nonagrigdp_2014) %>%
  filter(!is.na(nonagrigdp_2010) & !is.na(nonagrigdp_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "nonagrigdp_2010", "nonagrigdp_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = nonagrigdp)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Non-Agricultural GDP in Communities",
       x = "Non-Agricultural GDP",
       y = "Density",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         nonagrigdp_2010, nonagrigdp_2014) %>%
  filter(!is.na(nonagrigdp_2010) & !is.na(nonagrigdp_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "nonagrigdp_2010", "nonagrigdp_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         nonagrigdp = as.numeric(nonagrigdp)) %>%
  group_by(community, time) %>%
  summarise(mean_inc = mean(income, na.rm = T),
            mean_agrgdp = mean(nonagrigdp, na.rm=T)) %>%
  ggplot(aes(x = mean_agrgdp, y=mean_inc, color = time)) +
  xlim(0, 15000)+
  geom_smooth(method = "lm") +
  geom_point(alpha=0.2)+
  labs(title = "Personal Income vs. Non-Agricultural GDP in Communities",
       x = "Non-Agricultural GDP",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

```{r, echo=FALSE}
# Income per Capita
# Distribution
joined_n %>%
  select(community_2010, community_2014,
         incpercap_2010, incpercap_2014) %>%
  filter(!is.na(incpercap_2010) & !is.na(incpercap_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "incpercap_2010", "incpercap_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time)) %>%
  ggplot(aes(x = incpercap)) +
  geom_line(stat = "density", aes(color = time)) +
  labs(title = "Distribution of Income per capita in Communities",
       x = "Income per capita",
       y = "Density",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")

# Relationship
joined_n %>%
  select(community_2010, community_2014, 
         income_2010, income_2014,
         incpercap_2010, incpercap_2014) %>%
  filter(!is.na(incpercap_2010) & !is.na(incpercap_2014) & 
           !is.na(income_2010) & !is.na(income_2014)) %>%
  reshape(direction = "long",
          varying = c("community_2010", "community_2014",
                      "income_2010", "income_2014",
                      "incpercap_2010", "incpercap_2014"),
          sep = "_") %>%
  mutate(time = as.factor(time),
         incpercap = as.numeric(incpercap)) %>%
  group_by(community, time) %>%
  summarise(mean_inc = mean(income, na.rm = T),
            mean_agrgdp = mean(incpercap, na.rm=T)) %>%
  ggplot(aes(x = mean_agrgdp, y=mean_inc, color = time)) +
  geom_point(alpha = 0.1) +
  geom_smooth(alpha=0.3, span=0.3) +
  labs(title = "Personal Income vs. Income per capita in Communities",
       x = "Income per capita",
       y = "Personal Income",
       color = "Year",
       caption = "Unit: CNY\nSource: China Family Panel Studies")
```

## Linear Regression Model
```{r, echo=FALSE, eval=FALSE}
# Run linear model for panel data with interested variables
did.reg <- plm(log(income+(exp(-5)))~gender+I(age)+I(age^2)+educ+numconvenience
               +numprimarysch+numhospital+watersource+pop
                +timecommittenearesttown+timecommittecountycap
                +agrigdp+nonagrigdp+incpercap+year, data = dt, model = "within")

# Change the coefficient names for interpretability
varnames<-c("Gender","Age","Age^2","Education","Number of primary school",
            "Number of hospitals","Well/Spring water","Tap water","Cellar water",
            "Other","Well","Pond/Spring water","Population",
            "Time to travel to nearest towm","Time to travel county",
            "Agricultural GDP","Non-agricultural GDP","Income per Capita","Year 2014")
names(did.reg$coefficients)<-varnames
```

### Correlation Plot
```{r, echo=FALSE,fig.align='left'}
# Set the custom palette for the scale for correlation plot
col3 <- colorRampPalette(c("#F8766D","white","#00BFC4")) 
# Correlation Plot
corrplot(cor(dt_cor),method = "color",tl.col = "gray30", tl.srt = 45,
                   tl.cex = 0.75, cl.cex = 0.75, col = col3(100), 
                  cl.col = "gray30", mar=c(0,0,0,0))
```

### Coefficient Plot
```{r, echo=FALSE, fig.height=6, fig.width=6,fig.align='left'}
# Coefficient Plot
coefplot(did.reg, decreasing = TRUE, lwdInner=0.5, pointSize = 2,
         color ="#00BFC4", xlab = "",ylab="", title = "" )  
```
